### ISSUE TITLE
Fix application error: a server-side exception has occurred (see the server logs for more information). Digest: 2334254660

### ISSUE THREAD

**Issue by mehradi-github** [the-thaqalayn/the-quran-frontend-next#57]
PrismaClientInitializationError: 
Invalid `prisma.verse.findMany()` invocation:

Error querying the database: Error code 14: Unable to open the database file
    at In.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:122:7154)
    at In.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/var/task/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async d (/var/task/.next/server/app/[id]/page.js:1:18005) {
  clientVersion: '5.12.0',
  errorCode: undefined
}

[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '2334254660'
}

**Comment by mehradi-github** [comment]
[Erorr Link](https://quran-v3.vercel.app/1)
